receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

  prometheus:
    config:
      scrape_configs:
        - job_name: post-service
          metrics_path: /actuator/prometheus
          static_configs:
            - targets: ["post-service:8001"]

        - job_name: comment-service
          metrics_path: /actuator/prometheus
          static_configs:
            - targets: ["comment-service:8002"]

processors:
  batch:
    send_batch_size: 5
    send_batch_max_size: 10
    timeout: 2s

exporters:
  logging:
    loglevel: debug
  otlp/tempo:
    endpoint: http://tempo:4317
    tls:
      insecure: true
  prometheusremotewrite:
    endpoint: "http://prometheus:9090/api/v1/write"
    tls:
      insecure: true
    resource_to_telemetry_conversion:
      enabled: true

extensions:
  zpages:
    endpoint: 0.0.0.0:55679

service:
  extensions: [zpages]
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch ]
      exporters: [ logging, otlp/tempo ]
    metrics:
      receivers: [otlp, prometheus]
      processors: [batch]
      exporters: [prometheusremotewrite]