spring:
  output:
    ansi:
      enabled: always
  application:
    name: post-service

server:
  port: ${PORT:8001}

management:
  endpoints:
    beans:
      enabled: true
    web:
      exposure:
        include: configprops, env, health, heapdump, info, loggers, mappings, prometheus
  endpoint:
    health:
      show-details: always
      show-components: always
      probes:
        enabled: true
  info:
    env:
      enabled: true
    java:
      enabled: true
    os:
      enabled: true
  metrics:
    tags:
      application: ${spring.application.name}
  tracing:
    enabled: true
    sampling.probability: 1.0

otel.exporter.otlp.traces.endpoint: http://localhost:4317

logging.pattern.level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"

comment-service:
  base-url: http://localhost:8002